[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
self_update = { version = "0.40.0", features = ["archive-tar"] }
self-replace = "1.3.7"
tempfile = "3.10.1"
reqwest = "0.12.5"
