[package]
name = "test"
version = "0.1.26"
edition = "2021"

[dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }

self_update = { version = "0.40.0", features = [
    "archive-tar",
    "compression-flate2",
] }
self-replace = "1.3.7"
tempfile = "3.10.1"
reqwest = "0.12.5"
