import { Button, VerticalBox} from "std-widgets.slint";

export component MainWindow inherits Window {
    title: "Update Helper";
    background: #3b3b3b;

    in property <string> update_button_text: "Check for Update";
    in property <string> log: "";

    in property <bool> checking: false;
    in property <bool> self_updateing: false;

    callback check-update();
    callback self-update();

    VerticalLayout {
        padding: 7px;

        Button {
            text: root.update_button_text;
            enabled: {
                !root.checking && root.update_button_text != "Up to date";
            }
            clicked => {
                root.check-update();
            }
        }

        VerticalBox {
            Text {
                color: #fff;
                text: "Log:";
            }

            Rectangle {
                background: #2b2b2b;
                Text {
                    color: #fff;
                    text: root.log;
                }
            }
        }
    }
}
