name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: echo
      - run: echo "......$github.event_name......."
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.ref }}"
      - run: docker -v
      - run: echo "............."
        
        
