name: Build

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        if: github.event_name != 'schedule'
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta pihole
        id: pihole_meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            pihole/pihole
            ghcr.io/pi-hole/pihole
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            type=schedule
            type=ref,event=branch,enable=${{ github.event_name != 'schedule' }}
            type=ref,event=tag
      -
        name: "Echo"
        run: |
          echo "github.event_name"
          ${{ github.event_name }}
          echo "..........."
          echo "tags"
          ${{ steps.pihole_meta.outputs.tags }}
          echo "..........."
          echo "labels"
          ${{ steps.pihole_meta.outputs.labels }}
