name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: echo
        run: |
          echo "..."
          current_timezone=$(timedatectl | grep "Time zone" | awk '{print $3}')
          echo "$current_timezone"
          echo "..."

