name: touch ls

on:
  workflow_dispatch:
  
jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      -
        name: touch
        run: |
            touch test123.txt
  
  his_touch_available_touch:
    runs-on: ubuntu-latest
    needs: touch
    steps:
      -
        name: ls
        run: |
            ls -al
