name: Release Checker

on:
  workflow_dispatch:
  
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        run: |
            echo ${{ vars.DOCKERHUB_NAMESPACE }}

