name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: echo
        run:
          echo "......$github.event_name......."
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"
          docker -v
          echo "............."
        
        
