name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
       -
        name: echo
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "..."
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/ChaseCares/yet-another-pihole-dot-doh/tags/protection
          echo "..."

