name: Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: echo
        run: |
          echo "..."
          echo -e "\e[31mTest\e[0m"
          echo "..."

